# Generated by Django 4.0.4 on 2022-05-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='email_id',
            new_name='email',
        ),
    ]
